import logging
from pathlib import Path
from typing import Union

from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.core.signing import TimestampSigner
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.template import Context, Template
from django.utils.http import url_has_allowed_host_and_scheme
from gotenberg_client import GotenbergClient
from gotenberg_client.options import (
    Measurement,
    PageMarginsType,
    PageOrientation,
    PageSize,
)

from registration import mqtt
from registration.models import Badge, Dealer, Firebase, PrintHistory, Staff

logger = logging.getLogger(__name__)


def _safe_internal_url(url: str, request: HttpRequest) -> str:
    """Return ``url`` only if it is a same-origin http(s) URL (or a relative
    path on this host). Anything else — javascript:, protocol-relative,
    cross-origin — collapses to "" so the caller never renders it.

    OWASP "Unvalidated Redirects and Forwards" cheat sheet, ASVS V5.1.5.
    """
    if not url:
        return ""
    if url_has_allowed_host_and_scheme(
        url,
        allowed_hosts={request.get_host()},
        require_https=request.is_secure(),
    ):
        return url
    return ""


@staff_member_required
def printNametag(request):
    # `file` and `next` are server-supplied in normal flows (built by
    # registration.views.onsite_admin and admin.py via reverse() + urlencode)
    # but the URL is reachable directly. Validate both as same-origin
    # http(s) URLs / relative paths before rendering. The template renders
    # them via {% json_script %} so the JS string-context XSS vector is
    # closed regardless, but defense-in-depth: don't trust the GET params.
    context = {
        "printing_data": {
            "file": _safe_internal_url(request.GET.get("file", ""), request),
            "next": _safe_internal_url(request.GET.get("next", ""), request),
        },
    }
    # Keep `next` available for the template's <a> Go-Back link, where
    # auto-escape provides the HTML-context defense and our same-origin
    # validation provides the URL-scheme defense.
    context["next"] = context["printing_data"]["next"]
    return render(request, "registration/printing.html", context)


# servePDF is intentionally NOT @staff_member_required: the security model is
# a Capability URL — every fetch carries a TimestampSigner-signed payload
# (60s max-age, see signer.unsign_object call below) generated by an
# authenticated staff endpoint (onsite_print_badges / admin print_badges).
# This shape is required so kiosk printers — which run unauthenticated —
# can dereference URLs handed to them by staff. ASVS V2.10.4 (token
# integrity) + V3.4 (short-lived) cover this design. Do not add
# session-based auth here without re-evaluating the kiosk flow.
def servePDF(request: HttpRequest) -> Union[HttpResponse, JsonResponse]:
    data = request.GET.get("data", None)
    if not data:
        return JsonResponse({"success": False, "reason": "Missing data"}, status=400)

    signer = TimestampSigner()
    try:
        data_obj = signer.unsign_object(data, max_age=60)
    except:
        return JsonResponse({"success": False, "reason": "Invalid data"}, status=401)

    badge_ids = data_obj.get("badge_ids", [])
    queryset = Badge.objects.filter(id__in=badge_ids)

    badge_groups = {}
    badge_templates = {}

    for badge in queryset:
        level = badge.effectiveLevel()
        if not level or level == Badge.UNPAID:
            messages.warning(
                request, f"skipped printing {badge} because level is {level}"
            )
            continue

        badge_template = badge.event.defaultBadgeTemplate
        if badge_template.id not in badge_templates:
            badge_groups[badge_template.id] = []
            badge_templates[badge_template.id] = (
                badge_template,
                Template(badge_template.template),
            )

        level = str(level)
        if staff := Staff.objects.filter(
            attendee=badge.attendee, event=badge.event
        ).first():
            level = "Staff"

            if not staff.checkedIn and data_obj["source"] == PrintHistory.ONSITE:
                staff.checkedIn = True
                staff.save()

        elif Dealer.objects.filter(attendee=badge.attendee, event=badge.event).exists():
            level = "Dealer"

        badge_groups[badge_template.id].append(
            {
                "name": badge.badgeName,
                "level": level,
                "number": badge.badgeNumber,
            }
        )

    with GotenbergClient(settings.GOTENBERG_HOST) as client:
        pdfs = []

        for badge_template_id, badges in badge_groups.items():
            badge_template, template = badge_templates[badge_template_id]
            context = Context({"badges": badges})
            rendered = str(template.render(context))

            with client.chromium.html_to_pdf() as route:
                response = (
                    route.size(
                        PageSize(
                            Measurement(badge_template.paperWidth),
                            Measurement(badge_template.paperHeight),
                        )
                    )
                    .margins(
                        PageMarginsType(
                            Measurement(badge_template.marginTop),
                            Measurement(badge_template.marginBottom),
                            Measurement(badge_template.marginLeft),
                            Measurement(badge_template.marginRight),
                        )
                    )
                    .orient(
                        PageOrientation(
                            PageOrientation.Landscape
                            if badge_template.landscape
                            else PageOrientation.Portrait
                        )
                    )
                    .scale(badge_template.scale)
                    .string_resource(rendered, "index.html")
                    .render_expression("window.badgeReady === true")
                    .run()
                )
                pdfs.append(response.content)

        finalPdf = None

        if len(pdfs) == 0:
            return JsonResponse(
                {"success": False, "reason": "No PDFs were generated"}, status=404
            )
        elif len(pdfs) == 1:
            finalPdf = pdfs[0]
        else:
            with client.merge.merge() as route:
                req = route
                for index, badgePdf in enumerate(pdfs):
                    req._add_in_memory_file(badgePdf, name=f"{index}.pdf")
                response = req.run()
                finalPdf = response.content

    http_resp = HttpResponse()
    http_resp["content-type"] = "application/pdf"
    http_resp.write(finalPdf)

    terminal = None
    if terminal_name := data_obj.get("terminal", None):
        terminal = Firebase.objects.get(name=terminal_name)

    for badge in queryset:
        badge.printed = True
        badge.save()
        PrintHistory.objects.create(
            badge=badge, firebase=terminal, source=data_obj["source"]
        )

    if terminal:
        mqtt.send_mqtt_message(mqtt.get_topic("web/refresh", name=terminal.name))

    return http_resp
