"""PayPal-native webhook event handlers.

One function per PayPal event type. Each handler takes a
``PaymentWebhookNotification`` row and returns ``True`` when it processed the
event against a local ``Order``, ``False`` when it could not (e.g. the order
referenced by the webhook is not in our database, or the payload is
malformed). The caller is responsible for persisting ``processed`` on the
notification.

Square webhooks are handled separately in :mod:`registration.payments` and
are not affected by anything in this module.

PayPal API references used while writing these handlers:

- Orders V2 (create/capture): https://developer.paypal.com/docs/api/orders/v2/
- Payments V2 (refund/capture): https://developer.paypal.com/docs/api/payments/v2/
- Payments V1 (legacy sale/refund shape):
  https://developer.paypal.com/docs/api/payments/v1/
- Customer Disputes V1:
  https://developer.paypal.com/docs/api/customer-disputes/v1/
- Webhook event names catalog:
  https://developer.paypal.com/api/rest/webhooks/event-names/
"""

import logging
from datetime import datetime
from decimal import Decimal

from registration import tasks
from registration.models import (
    BanList,
    Order,
    OrderItem,
    PaymentWebhookNotification,
    get_hold_type,
)

logger = logging.getLogger(__name__)


# Refund status values that reduce Order.total. COMPLETED funds have moved;
# PENDING refunds (e.g. eCheck) have not cleared yet but PayPal has committed
# to refunding once the rail settles. CANCELLED/FAILED refunds never happen.
_EFFECTIVE_REFUND_STATUSES = {"COMPLETED", "PENDING"}


# PayPal v1 (legacy) refund `state` strings mapped to v2 `status` enum values.
# See https://developer.paypal.com/docs/api/quickstart/refund-payment/ for the
# legacy lower-case vocabulary.
_V1_STATE_TO_V2_STATUS = {
    "completed": "COMPLETED",
    "pending": "PENDING",
    "cancelled": "CANCELLED",
    "failed": "FAILED",
}


# Dispute outcome_code -> Order.status. Source:
# https://developer.paypal.com/docs/disputes/disputes-reference/
_DISPUTE_OUTCOME_TO_ORDER_STATUS = {
    "RESOLVED_BUYER_FAVOUR": Order.DISPUTE_LOST,
    "RESOLVED_WITH_REFUND": Order.DISPUTE_LOST,
    "RESOLVED_SELLER_FAVOUR": Order.DISPUTE_WON,
    "DENIED": Order.DISPUTE_WON,
    "CANCELED_BY_BUYER": Order.DISPUTE_WON,
    "NONE": Order.DISPUTE_WON,
    "ACCEPTED": Order.DISPUTE_ACCEPTED,
}


# ---------------------------------------------------------------------------
# Order lookup
# ---------------------------------------------------------------------------


def _find_order_by_reference(candidate: str | None) -> Order | None:
    """Return the first Order whose ``reference`` matches ``candidate``.

    ``reference`` is the confirmation token generated at checkout time and
    passed through to PayPal as the purchase unit's ``invoice_id`` and
    ``custom_id`` (see :func:`registration.paypal_payments.create_unpaid_paypal_order`).
    Every downstream refund, capture reversal and dispute event echoes it
    back, so this is the preferred path.
    """
    if not candidate:
        return None
    return Order.objects.filter(reference=candidate).first()


def _find_order_by_capture_id(capture_id: str | None) -> Order | None:
    """Fallback lookup: scan ``apiData`` for a matching capture ID.

    Used when an event was generated by PayPal before ``invoice_id``/
    ``custom_id`` was being propagated (legacy orders predating the
    ``apis_reference`` plumbing in :func:`create_unpaid_paypal_order`), or
    when the webhook resource does not carry those fields.
    """
    if not capture_id:
        return None
    for order in Order.objects.all():
        if not order.apiData or not isinstance(order.apiData, dict):
            continue
        try:
            purchase_units = order.apiData.get("purchase_units") or []
            if not purchase_units:
                continue
            captures = (purchase_units[0] or {}).get("payments", {}).get("captures") or []
        except (AttributeError, IndexError, TypeError):
            continue
        if any(c.get("id") == capture_id for c in captures):
            return order
    return None


def _parse_capture_id_from_links(resource: dict) -> str | None:
    """Extract the parent capture ID from a v2 Refund resource's HATEOAS links.

    PayPal's v2 Refund schema carries ``links`` with ``rel=up`` pointing at
    ``/v2/payments/captures/<capture_id>`` (see section 1.4 of the PayPal
    reference research doc). Returns the capture ID portion of the URL, or
    ``None`` if the link is absent or malformed.
    """
    for link in resource.get("links") or []:
        if link.get("rel") == "up" and link.get("href"):
            href = link["href"]
            try:
                tail = href.rsplit("/captures/", 1)[1]
            except IndexError:
                continue
            return tail.split("?", 1)[0].split("/", 1)[0] or None
    return None


def _find_order_for_v2_refund(resource: dict) -> Order | None:
    """Resolve the Order for a v2 refund resource (PAYMENT.CAPTURE.REFUNDED /
    PAYMENT.CAPTURE.REVERSED)."""
    order = _find_order_by_reference(resource.get("invoice_id"))
    if order:
        return order
    order = _find_order_by_reference(resource.get("custom_id"))
    if order:
        return order
    return _find_order_by_capture_id(_parse_capture_id_from_links(resource))


def _find_order_for_v1_sale(resource: dict) -> Order | None:
    """Resolve the Order for a v1 sale-refund resource (PAYMENT.SALE.REFUNDED)."""
    order = _find_order_by_reference(resource.get("invoice_number"))
    if order:
        return order
    return _find_order_by_reference(resource.get("custom"))


def _find_order_for_dispute(resource: dict) -> Order | None:
    """Resolve the Order for a CUSTOMER.DISPUTE.* resource."""
    transactions = resource.get("disputed_transactions") or []
    first = transactions[0] if transactions else {}
    order = _find_order_by_reference(first.get("custom"))
    if order:
        return order
    order = _find_order_by_reference(first.get("invoice_number"))
    if order:
        return order
    return _find_order_by_capture_id(first.get("seller_transaction_id"))


# ---------------------------------------------------------------------------
# Refund application
# ---------------------------------------------------------------------------


def _reset_donations_if_insufficient(order: Order) -> None:
    """Zero out org/charity donations when the remaining order total cannot
    cover them. Mirrors the rule in
    :func:`registration.paypal_payments.update_order_refund_data`.
    """
    if order.orgDonation + order.charityDonation > order.total:  # ty:ignore[unsupported-operator]
        order.orgDonation = Decimal("0")
        order.charityDonation = max(order.total, Decimal("0"))
        message = (
            "\nWarning: Refunded order has caused charity and organization "
            "donation amounts to reset.\n"
        )
        logger.warning(message.strip())
        order.notes = (order.notes or "") + message


def _refund_reduces_total(status: str) -> bool:
    return status.upper() in _EFFECTIVE_REFUND_STATUSES


def _upsert_refund_in_apidata(order: Order, refund: dict) -> str | None:
    """Insert or update ``refund`` in ``order.apiData['refunds']``.

    Dedup is keyed on ``refund["id"]`` because PayPal may deliver the same
    refund resource through multiple webhook notifications (state transition
    PENDING -> COMPLETED, or simple redelivery with a different notification
    id). Returns the *previous* status of the refund if it already existed,
    or ``None`` if this is a new refund.
    """
    if not isinstance(order.apiData, dict):
        order.apiData = {}
    refunds = order.apiData.get("refunds") or []  # ty:ignore[unresolved-attribute]
    refund_id = refund.get("id")
    previous_status: str | None = None
    replaced = False
    for i, existing in enumerate(refunds):
        if existing.get("id") == refund_id:
            previous_status = existing.get("status")
            refunds[i] = refund
            replaced = True
            break
    if not replaced:
        refunds.append(refund)
    order.apiData["refunds"] = refunds  # ty:ignore[invalid-assignment]
    return previous_status


def _apply_refund_side_effects(
    order: Order,
    status: str,
    amount: Decimal,
    previous_status: str | None,
) -> None:
    """Update order.status and order.total based on the refund state transition.

    Total adjustment uses a delta: reducing total is pending/completed, leaving
    total alone is cancelled/failed. A transition between the two classes
    adjusts the total accordingly so an unwound refund restores the original
    amount.
    """
    status = status.upper()
    new_effective = amount if _refund_reduces_total(status) else Decimal("0")
    old_effective = (
        amount if previous_status and _refund_reduces_total(previous_status) else Decimal("0")
    )
    delta = new_effective - old_effective
    if delta:
        order.total = (order.total or Decimal("0")) - delta
        _reset_donations_if_insufficient(order)

    if status == "COMPLETED":
        order.status = Order.REFUNDED
    elif status == "PENDING":
        order.status = Order.REFUND_PENDING
    elif (
        status in ("CANCELLED", "FAILED")
        and previous_status
        and previous_status.upper() in _EFFECTIVE_REFUND_STATUSES
    ):
        # The refund we previously applied is no longer happening; undo.
        order.status = Order.COMPLETED


def _apply_v2_refund(
    order: Order,
    resource: dict,
    reversal: bool = False,
) -> None:
    """Upsert a v2 Refund and apply its side effects to ``order``.

    ``reversal=True`` flags the stored record to distinguish PayPal-initiated
    reversals from merchant-initiated refunds for auditing purposes; it does
    not change status/total math (per the PayPal contract both events carry a
    v2 Refund resource with the same shape).
    """
    stored = dict(resource)
    if reversal:
        stored["reversal"] = True
    previous_status = _upsert_refund_in_apidata(order, stored)
    amount_value = (resource.get("amount") or {}).get("value") or "0"
    _apply_refund_side_effects(
        order, resource.get("status") or "", Decimal(str(amount_value)), previous_status
    )


# ---------------------------------------------------------------------------
# Public handlers — one per PayPal event type
# ---------------------------------------------------------------------------


def handle_capture_refunded(notification: PaymentWebhookNotification) -> bool:
    """PAYMENT.CAPTURE.REFUNDED — merchant- or API-initiated refund.

    Per the PayPal webhook catalog the resource is a v2 Refund object. The
    ``status`` field carries the life cycle state (COMPLETED, PENDING,
    CANCELLED, FAILED); pending/failed refunds are NOT separate event types.
    """
    resource = notification.body.get("resource")
    if not isinstance(resource, dict):
        logger.warning("PAYMENT.CAPTURE.REFUNDED: missing resource")
        return False
    order = _find_order_for_v2_refund(resource)
    if not order:
        logger.warning(
            "PAYMENT.CAPTURE.REFUNDED for refund %s: no matching order",
            resource.get("id"),
        )
        return False
    _apply_v2_refund(order, resource, reversal=False)
    order.save()
    return True


def handle_capture_reversed(notification: PaymentWebhookNotification) -> bool:
    """PAYMENT.CAPTURE.REVERSED — PayPal-initiated reversal (chargeback outcome).

    Despite the event name the resource PayPal attaches is a v2 Refund object
    (confirmed by real sanitized payloads such as
    https://github.com/woocommerce/woocommerce-paypal-payments/issues/1614).
    """
    resource = notification.body.get("resource")
    if not isinstance(resource, dict):
        logger.warning("PAYMENT.CAPTURE.REVERSED: missing resource")
        return False
    order = _find_order_for_v2_refund(resource)
    if not order:
        logger.warning(
            "PAYMENT.CAPTURE.REVERSED for refund %s: no matching order",
            resource.get("id"),
        )
        return False
    _apply_v2_refund(order, resource, reversal=True)
    order.save()
    return True


def handle_sale_refunded_v1(notification: PaymentWebhookNotification) -> bool:
    """PAYMENT.SALE.REFUNDED — legacy v1 sale-world refund event.

    PayPal may still emit v1 events for some merchants even on v2 integrations.
    The v1 resource uses different field names (``state`` lowercase,
    ``amount.total``/``amount.currency``, ``custom``/``invoice_number``,
    ``sale_id``/``parent_payment``) — normalize here and reuse the v2
    side-effects machinery.
    """
    resource = notification.body.get("resource")
    if not isinstance(resource, dict):
        logger.warning("PAYMENT.SALE.REFUNDED: missing resource")
        return False
    order = _find_order_for_v1_sale(resource)
    if not order:
        logger.warning(
            "PAYMENT.SALE.REFUNDED for refund %s: no matching order",
            resource.get("id"),
        )
        return False

    v1_amount = resource.get("amount") or {}
    normalized = {
        "id": resource.get("id"),
        "status": _V1_STATE_TO_V2_STATUS.get((resource.get("state") or "").lower(), "COMPLETED"),
        "amount": {
            "value": v1_amount.get("total") or "0",
            "currency_code": v1_amount.get("currency") or "USD",
        },
        "custom_id": resource.get("custom"),
        "invoice_id": resource.get("invoice_number"),
        "create_time": resource.get("create_time"),
        "update_time": resource.get("update_time"),
        "_source": "v1_sale_refund",
    }
    _apply_v2_refund(order, normalized, reversal=False)
    order.save()
    return True


def _find_order_for_v2_capture(resource: dict) -> Order | None:
    """Resolve the Order for a v2 capture resource (PAYMENT.CAPTURE.COMPLETED /
    PAYMENT.CAPTURE.DENIED).
    """
    order = _find_order_by_reference(resource.get("invoice_id"))
    if order:
        return order
    order = _find_order_by_reference(resource.get("custom_id"))
    if order:
        return order
    return _find_order_by_capture_id(resource.get("id"))


def handle_capture_completed(notification: PaymentWebhookNotification) -> bool:
    """PAYMENT.CAPTURE.COMPLETED — primary payment capture confirmation.

    The synchronous capture in :func:`registration.paypal_payments.capture_paypal_payment`
    already sets ``Order.status = COMPLETED`` for the happy path. This handler
    is a safety net for captures that PayPal initially returned as PENDING
    (held for review, pending eCheck, etc.) and later cleared. Transitions
    PENDING -> COMPLETED and enqueues the registration email if one has not
    yet been sent.
    """
    resource = notification.body.get("resource")
    if not isinstance(resource, dict):
        logger.warning("PAYMENT.CAPTURE.COMPLETED: missing resource")
        return False
    order = _find_order_for_v2_capture(resource)
    if not order:
        logger.warning(
            "PAYMENT.CAPTURE.COMPLETED for capture %s: no matching order",
            resource.get("id"),
        )
        return False

    if order.status == Order.COMPLETED:
        return True

    if order.status in (
        Order.REFUNDED,
        Order.REFUND_PENDING,
        Order.DISPUTE_EVIDENCE_REQUIRED,
        Order.DISPUTE_PROCESSING,
        Order.DISPUTE_WON,
        Order.DISPUTE_LOST,
        Order.DISPUTE_ACCEPTED,
    ):
        logger.warning(
            "PAYMENT.CAPTURE.COMPLETED for order %s ignored: terminal status %s",
            order.reference,
            order.status,
        )
        return True

    previous_status = order.status
    order.status = Order.COMPLETED
    order.save()

    if previous_status == Order.PENDING and order.email_sent is None and order.billingEmail:
        try:
            tasks.send_registration_email_task.delay(order.id, order.billingEmail)  # ty:ignore[unresolved-attribute]
        except Exception:
            logger.exception(
                "Failed to queue registration email for late-completed order %s",
                order.id,  # ty:ignore[unresolved-attribute]
            )
    return True


def handle_capture_denied(notification: PaymentWebhookNotification) -> bool:
    """PAYMENT.CAPTURE.DENIED — capture was denied by PayPal.

    Mark the Order as FAILED so admins see it in reconciliation dashboards.
    Idempotent: no-op if the order is already FAILED.
    """
    resource = notification.body.get("resource")
    if not isinstance(resource, dict):
        logger.warning("PAYMENT.CAPTURE.DENIED: missing resource")
        return False
    order = _find_order_for_v2_capture(resource)
    if not order:
        logger.warning(
            "PAYMENT.CAPTURE.DENIED for capture %s: no matching order",
            resource.get("id"),
        )
        return False
    if order.status != Order.FAILED:
        order.status = Order.FAILED
        order.save()
    return True


def _add_attendees_to_banlist_and_hold(order: Order) -> None:
    dispute_hold = get_hold_type("Chargeback")
    for oi in OrderItem.objects.filter(order=order):
        attendee = oi.badge.attendee
        attendee.holdType = dispute_hold
        attendee.save()
        BanList.objects.get_or_create(
            email=attendee.email,
            defaults=dict(
                firstName=attendee.firstName,
                lastName=attendee.lastName,
                reason=f"Initiated chargeback [APIS {datetime.now().isoformat()}]",
            ),
        )


def handle_dispute_created(notification: PaymentWebhookNotification) -> bool:
    """CUSTOMER.DISPUTE.CREATED — buyer filed a dispute. Mark evidence required,
    apply a chargeback hold and ban-list entry to each attendee on the order,
    and queue the admin-notification email.
    """
    resource = notification.body.get("resource")
    if not isinstance(resource, dict):
        logger.warning("CUSTOMER.DISPUTE.CREATED: missing resource")
        return False
    order = _find_order_for_dispute(resource)
    if not order:
        logger.warning(
            "CUSTOMER.DISPUTE.CREATED for dispute %s: no matching order",
            resource.get("dispute_id"),
        )
        return False
    if not isinstance(order.apiData, dict):
        order.apiData = {}
    order.apiData["dispute"] = resource  # ty:ignore[invalid-assignment]
    order.status = Order.DISPUTE_EVIDENCE_REQUIRED
    order.save()
    _add_attendees_to_banlist_and_hold(order)
    try:
        tasks.send_chargeback_notice_email_task.delay(order.id)  # ty:ignore[unresolved-attribute]
    except Exception:
        # Queue backend may be down at webhook-receive time. The dispute
        # state is already persisted to the Order; log and continue so the
        # webhook is marked processed. Ops can re-trigger the email later.
        logger.exception("Failed to queue chargeback notice email for order %s", order.id)  # ty:ignore[unresolved-attribute]
    return True


def handle_dispute_updated(notification: PaymentWebhookNotification) -> bool:
    """CUSTOMER.DISPUTE.UPDATED — status/evidence/message change. Refresh stored
    dispute snapshot; do not re-apply holds (they were applied on CREATED).
    """
    resource = notification.body.get("resource")
    if not isinstance(resource, dict):
        logger.warning("CUSTOMER.DISPUTE.UPDATED: missing resource")
        return False
    order = _find_order_for_dispute(resource)
    if not order:
        logger.warning(
            "CUSTOMER.DISPUTE.UPDATED for dispute %s: no matching order",
            resource.get("dispute_id"),
        )
        return False
    if not isinstance(order.apiData, dict):
        order.apiData = {}
    order.apiData["dispute"] = resource  # ty:ignore[invalid-assignment]
    # Only flip to DISPUTE_PROCESSING when dispute is actively being worked on
    # by PayPal (buyer awaiting response, under review); preserve terminal
    # statuses set by the RESOLVED handler.
    if order.status not in (
        Order.DISPUTE_WON,
        Order.DISPUTE_LOST,
        Order.DISPUTE_ACCEPTED,
    ):
        status_value = (resource.get("status") or "").upper()
        if status_value in ("UNDER_REVIEW", "WAITING_FOR_BUYER_RESPONSE"):
            order.status = Order.DISPUTE_PROCESSING
    order.save()
    return True


def handle_dispute_resolved(notification: PaymentWebhookNotification) -> bool:
    """CUSTOMER.DISPUTE.RESOLVED — terminal. Map outcome_code to the matching
    Order.DISPUTE_* status. Reset donations when the outcome drops the order
    total (DISPUTE_LOST / DISPUTE_ACCEPTED).
    """
    resource = notification.body.get("resource")
    if not isinstance(resource, dict):
        logger.warning("CUSTOMER.DISPUTE.RESOLVED: missing resource")
        return False
    order = _find_order_for_dispute(resource)
    if not order:
        logger.warning(
            "CUSTOMER.DISPUTE.RESOLVED for dispute %s: no matching order",
            resource.get("dispute_id"),
        )
        return False
    if not isinstance(order.apiData, dict):
        order.apiData = {}
    order.apiData["dispute"] = resource  # ty:ignore[invalid-assignment]
    outcome = (resource.get("dispute_outcome") or {}).get("outcome_code") or ""
    order.status = _DISPUTE_OUTCOME_TO_ORDER_STATUS.get(outcome, Order.DISPUTE_PROCESSING)
    if order.status in (Order.DISPUTE_LOST, Order.DISPUTE_ACCEPTED) and (
        order.orgDonation > 0 or order.charityDonation > 0  # ty:ignore[unsupported-operator]
    ):
        order.notes = (order.notes or "") + (
            f"\n\nOriginal charity donation of ${order.charityDonation} and "
            f"organization donation of ${order.orgDonation} were reset due to "
            "lost or accepted dispute state."
        )
        order.orgDonation = Decimal("0")
        order.charityDonation = Decimal("0")
    order.save()
    return True
