# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 17:30
# Modified for Django 5.x on 2026-01-11


import datetime

from zoneinfo import ZoneInfo
from django.db import migrations, models


class Migration(migrations.Migration):

    DEFAULT_DATETIME = datetime.datetime.now().replace(tzinfo=ZoneInfo("US/Pacific"))

    dependencies = [
        ("registration", "0033_discount_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendeeRegEnd",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="attendeeRegStart",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="dealerRegEnd",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="dealerRegStart",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="onlineRegEnd",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="onlineRegStart",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="staffRegEnd",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="staffRegStart",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
    ]
