# Generated by Django 5.2 on 2026-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0110_add_trigram"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelevel",
            name="capacityDisplayThreshold",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="pricelevel",
            name="maxCapacity",
            field=models.IntegerField(
                blank=True, help_text="Leave blank for no limit", null=True
            ),
        ),
    ]
