# Generated by Django 6.0.4 on 2026-04-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0116a_add_trigram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentwebhooknotification",
            name="event_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
