# Generated by Django 6.0.4 on 2026-04-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0118_order_email_tracking"),
        ("registration", "0119_pricelevel_remainingslots_reservedslots"),
    ]

    operations = []
