# Generated by Django 6.0.4 on 2026-05-10
#
# Audit P1.7: Replace the global unique constraint on
# PaymentWebhookNotification.event_id with a composite uniqueness on
# (integration, event_id). A PayPal id colliding with a Square event_id
# previously caused one of the two events to be silently dropped.
#
# This migration was generated via `manage.py makemigrations` — three
# AlterField operations on Event (dealerEmail/registrationEmail/staffEmail)
# were stripped because they were artifacts of APIS_DEFAULT_EMAIL being
# read at model-definition time during the makemigrations run, not real
# schema changes.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0120_merge_20260423_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentwebhooknotification",
            name="event_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="paymentwebhooknotification",
            constraint=models.UniqueConstraint(
                fields=("integration", "event_id"),
                name="unique_integration_event_id",
            ),
        ),
    ]
