# Generated by Django 6.1 on 2026-08-23 23:35

import django.db.models.deletion
import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0124_event_email_callable_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_id', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=registration.models.badge_bg_file_name)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.badgebackground'),
        ),
        migrations.AddConstraint(
            model_name='badgebackground',
            constraint=models.UniqueConstraint(fields=('event_id', 'letter_id'), name='unique_badge_bg_letter_per_event_id'),
        ),
    ]
