# Generated by Django 6.1 on 2026-08-15 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0124_event_email_callable_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(default='Furpocalypse 2026', on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
            preserve_default=False,
        ),
    ]
