# Generated by Django 6.1 on 2026-08-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0127_alter_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
    ]
