"""
Django settings for fm_eventmanager project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from idempotency_key import status

eval_bool = lambda x: x.lower() in ("true", "1", "t", "y", "yes")

SENTRY_ENABLED = eval_bool(os.environ.get("SENTRY_ENABLED", ""))
if SENTRY_ENABLED:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    def _sentry_before_send(event, hint):
        request = (event or {}).get("request") or {}
        request.pop("data", None)
        request.pop("cookies", None)
        headers = request.get("headers") or {}
        for hkey in list(headers):
            if hkey.lower() in {
                "authorization",
                "cookie",
                "x-csrftoken",
                "idempotency-key",
                "x-firebase-token",
            }:
                headers[hkey] = "[scrubbed]"
        return event

    sentry_sdk.init(
        dsn=os.environ["SENTRY_DSN"],
        integrations=[DjangoIntegration()],
        traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", 0.01)),
        send_default_pii=eval_bool(os.environ.get("SENTRY_SEND_DEFAULT_PII", "False")),
        before_send=_sentry_before_send,
        auto_session_tracking=False,
    )

    SENTRY_RELEASE = os.environ.get("SENTRY_RELEASE", "local")
    SENTRY_ENVIRONMENT = os.environ.get("SENTRY_ENVIRONMENT")
    SENTRY_FRONTEND_DSN = os.environ.get("SENTRY_FRONTEND_DSN")
    SENTRY_USER_REPORTS = True

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = eval_bool(os.getenv("DJANGO_DEBUG", "False"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            #'filters': ['require_debug_true'],
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "django": {
            "handlers": ["console"],
            "propagate": True,
        },
    },
}

# Get loglevel from env
LOGLEVEL = os.getenv("DJANGO_LOGLEVEL", "info").upper()

if eval_bool(os.getenv("APIS_ADMIN_EMAIL_HANDLER", "False")):
    ADMINS = [
        (
            os.getenv("APIS_ADMIN_NAME", os.getenv("APIS_ADMIN_EMAIL")),
            os.getenv("APIS_ADMIN_EMAIL"),
        ),
    ]
SERVER_EMAIL = os.getenv("DJANGO_SERVER_EMAIL", "no-reply@example.com")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", SERVER_EMAIL)


# ALLOWED_HOSTS / CSRF_TRUSTED_ORIGINS — mirror settings.py.
def _split_env(name):
    raw = os.environ.get(name, "")
    return [item.strip() for item in raw.split(",") if item.strip()]


ALLOWED_HOSTS = _split_env("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _split_env("CSRF_TRUSTED_ORIGINS")

if DEBUG:
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "testserver"]
    if not CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = ["http://localhost", "http://127.0.0.1"]
else:
    if not ALLOWED_HOSTS:
        raise RuntimeError(
            "ALLOWED_HOSTS must be set (comma-separated FQDNs) when DEBUG=False."
        )
    if not CSRF_TRUSTED_ORIGINS:
        raise RuntimeError(
            "CSRF_TRUSTED_ORIGINS must be set (comma-separated https:// origins) "
            "when DEBUG=False."
        )
    if any(h == "*" for h in ALLOWED_HOSTS):
        raise RuntimeError("ALLOWED_HOSTS must not contain '*' in production.")
    if any(o in ("http://*", "https://*", "*") for o in CSRF_TRUSTED_ORIGINS):
        raise RuntimeError(
            "CSRF_TRUSTED_ORIGINS must not contain wildcards in production."
        )

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    "django_admin_env_notice",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.postgres",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "widget_tweaks",
    "mathfilters",
    "import_export",
    "django_extensions",
    "maintenance_mode",
    "allauth",
    "allauth.account",
    "allauth.mfa",
    "registration",
    "nested_inline",
    "django_prometheus",
    "django_vite",
    "csp",
    "axes",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "fm_eventmanager.middleware.RequireClientIPMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "csp.middleware.CSPMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "idempotency_key.middleware.ExemptIdempotencyKeyMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    "axes.middleware.AxesMiddleware",
]

# django-debug-toolbar is dev-only; gate same as settings.py.
if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]
    _DT_MW = "debug_toolbar.middleware.DebugToolbarMiddleware"
    if _DT_MW not in MIDDLEWARE:
        MIDDLEWARE.insert(
            MIDDLEWARE.index("django.middleware.clickjacking.XFrameOptionsMiddleware")
            + 1,
            _DT_MW,
        )

ROOT_URLCONF = "fm_eventmanager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "maintenance_mode.context_processors.maintenance_mode",
                "registration.context_processors.square_environment",
                "django_admin_env_notice.context_processors.from_settings",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": os.getenv("DATABASE_NAME", "apis"),
        "USER": os.getenv("DATABASE_USER", "apis"),
        "PASSWORD": os.getenv("DATABASE_PASS", "secret"),
        "HOST": os.getenv("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT", "5432"),
        "OPTIONS": {
            "pool": eval_bool(os.getenv("DJANGO_DATABASE_POOL", "True")),
            "sslmode": os.getenv("DATABASE_SSLMODE", "prefer"),
        },
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("DJANGO_REDIS_URL", "redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": os.getenv("DJANGO_REDIS_KEY_PREFIX", "apis"),
    }
}


# Celery
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/2")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/2")
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_WORKER_SEND_TASK_EVENTS = eval_bool(
    os.getenv("CELERY_WORKER_SEND_TASK_EVENTS", "True")
)
CELERY_TASK_SEND_SENT_EVENT = eval_bool(
    os.getenv("CELERY_TASK_SEND_SENT_EVENT", "True")
)
# Match settings_test.py behavior: execute Celery tasks synchronously inside
# Django tests so ``.delay(...)`` dispatches hit ``mail.outbox`` and mocked
# task functions assertions fire before the HTTP response returns. Without
# this, tasks would enqueue to a real Redis broker that CI does not run.
CELERY_TASK_ALWAYS_EAGER = eval_bool(os.getenv("CELERY_TASK_ALWAYS_EAGER", "True"))
CELERY_TASK_EAGER_PROPAGATES = eval_bool(
    os.getenv("CELERY_TASK_EAGER_PROPAGATES", "True")
)


# Prometheus metrics
PROMETHEUS_METRICS_EXPORT_PORT_RANGE = range(81, 90)
PROMETHEUS_METRICS_EXPORT_ADDRESS = os.getenv(
    "PROMETHEUS_METRICS_EXPORT_ADDRESS", "127.0.0.1"
)


# Password validation: mirror settings.py.
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TZ", "UTC")

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_ADAPTER = "fm_eventmanager.adapters.account.RegistrationAccountAdapter"

# axes — mirror settings.py.
AXES_FAILURE_LIMIT = int(os.getenv("AXES_FAILURE_LIMIT", "5"))
AXES_COOLOFF_TIME = int(os.getenv("AXES_COOLOFF_TIME_HOURS", "1"))
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_CALLABLE = None
AXES_CLIENT_IP_CALLABLE = "fm_eventmanager.middleware.axes_client_ip"
AXES_HANDLER = "axes.handlers.database.AxesDatabaseHandler"

# Disable allauth's login_failed rate limit; axes covers it.
ACCOUNT_RATE_LIMITS = {
    "login_failed": "",
    "signup": "20/m/ip",
    "reset_password": "20/m/ip,5/m/key",
    "reset_password_from_key": "20/m/ip",
    "manage_email": "10/m/user",
    "change_password": "5/m/user",
    "change_phone": "1/m/user",
    "request_login_code": "20/m/ip,3/m/key",
    "login": "30/m/ip",
    "reauthenticate": "10/m/user",
    "confirm_email": "1/180s/key",
    "verify_phone": "1/30s/key,3/m/ip",
}

MFA_SUPPORTED_TYPES = ["totp", "webauthn", "recovery_codes"]
MFA_PASSKEY_LOGIN_ENABLED = True
MFA_ADAPTER = "allauth.mfa.adapter.DefaultMFAAdapter"

ALLAUTH_TRUSTED_CLIENT_IP_HEADER = os.getenv("TRUSTED_CLIENT_IP_HEADER", "X-Real-IP")

LOGIN_REDIRECT_URL = "admin:index"

IDEMPOTENCY_KEY = {
    # Specify the key encoder class to be used for idempotency keys.
    # If not specified then defaults to 'idempotency_key.encoders.BasicKeyEncoder'
    "ENCODER_CLASS": "idempotency_key.encoders.BasicKeyEncoder",
    # Set the response code on a conflict.
    # If not specified this defaults to HTTP_409_CONFLICT
    # If set to None then the original request's status code is used.
    "CONFLICT_STATUS_CODE": status.HTTP_409_CONFLICT,
    # Allows the idempotency key header sent from the client to be changed
    "HEADER": "HTTP_IDEMPOTENCY_KEY",
    "STORAGE": {
        # Specify the storage class to be used for idempotency keys
        # If not specified then defaults to 'idempotency_key.storage.MemoryKeyStorage'
        "CLASS": "idempotency_key.storage.CacheKeyStorage",
        # Name of the django cache configuration to use for the CacheStorageKey storage
        # class.
        # This can be overriden using the @idempotency_key(cache_name='MyCacheName')
        # view/viewset function decorator.
        "CACHE_NAME": "default",
        # When the response is to be stored you have the option of deciding when this
        # happens based on the responses status code. If the response status code
        # matches one of the statuses below then it will be stored.
        # The statuses below are the defaults used if this setting is not specified.
        "STORE_ON_STATUSES": [
            status.HTTP_200_OK,
            status.HTTP_201_CREATED,
            status.HTTP_202_ACCEPTED,
            status.HTTP_203_NON_AUTHORITATIVE_INFORMATION,
            status.HTTP_204_NO_CONTENT,
            status.HTTP_205_RESET_CONTENT,
            status.HTTP_206_PARTIAL_CONTENT,
            status.HTTP_207_MULTI_STATUS,
        ],
    },
    # The following settings deal with the process/thread lock that can be placed around the cache storage object
    # to ensure that multiple threads do not try to call the same view/viewset method at the same time.
    "LOCK": {
        # Specify the key object locking class to be used for locking access to the cache storage object.
        # If not specified then defaults to 'idempotency_key.locks.basic.ThreadLock'
        "CLASS": "idempotency_key.locks.redis.MultiProcessRedisLock",
        # Location of the Redis server if MultiProcessRedisLock is used otherwise this is ignored.
        # The host name can be specified or both the host name and the port separated by a colon ':'
        "LOCATION": os.getenv("IDEMPOTENCY_KEY_LOCK_LOCATION", "redis://redis:6379"),
        # The unique name to be used across processes for the lock. Only used by the MultiProcessRedisLock class
        "NAME": os.getenv("IDEMPOTENCY_KEY_LOCK_NAME", "APISLock"),
        # The maximum time to live for the lock. If a lock is given and is never released this timeout forces the release
        # The lock time is in seconds and the default is None which means lock until it is manually released
        "TTL": None,
        # The use of a lock around the storage object so that only one thread at a time can access it.
        # By default this is set to true. WARNING: setting this to false may allow duplicate calls to occur if the timing
        # is right.
        "ENABLE": True,
        # If the ENABLE_LOCK setting is True above then this represents the timeout (in seconds as a floating point number)
        # to occur before the thread gives up waiting. If a timeout occurs the middleware will return a HTTP_423_LOCKED
        # response.
        "TIMEOUT": 0.1,
    },
}

# Maintenance mode — mirror settings.py: use the Redis cache
# backend so state survives restarts and works under read-only root fs.
MAINTENANCE_MODE_STATE_BACKEND = os.getenv(
    "MAINTENANCE_MODE_STATE_BACKEND",
    "maintenance_mode.backends.CacheBackend",
)
MAINTENANCE_MODE_STATE_FILE_PATH = os.getenv(
    "MAINTENANCE_MODE_STATE_FILE_PATH",
    "/tmp/maintenance_mode_state.txt",
)
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True
MAINTENANCE_MODE_IGNORE_URLS = ("^/accounts/",)

if DEBUG:
    # Adds docker NAT routers and any internal upstream proxies as internal IPs to enable the debug toolbar
    import socket  # only if you haven't already imported this

    INTERNAL_IPS = ["127.0.0.1"]
    for proxy_host in (socket.gethostname(), os.getenv("INTERNAL_PROXY_HOST")):
        if proxy_host:
            hostname, _, ips = socket.gethostbyname_ex(proxy_host)
            INTERNAL_IPS += [ip[: ip.rfind(".")] + ".1" for ip in ips] + ips

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", "/app/apis/static/")
# NOTE: no STATICFILES_DIRS("bundler", ...) — AppDirectoriesFinder picks up
# ``registration/static/bundler/`` (Vite's output) automatically. See the
# equivalent note in settings.py.

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "fm_eventmanager.file_storage.SelectiveManifestStaticFilesStorage",
    },
}

# Cookie / transport hardening — mirror settings.py.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", str(60 * 60 * 24 * 365)))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = eval_bool(
        os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True")
    )
    SECURE_HSTS_PRELOAD = eval_bool(os.getenv("SECURE_HSTS_PRELOAD", "False"))

# CSP — mirror settings.py.
_CSP_REPORT_URI = os.getenv("CSP_REPORT_URI", "")
CONTENT_SECURITY_POLICY_REPORT_ONLY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        "script-src": [
            "'self'",
            "https://web.squarecdn.com",
            "https://sandbox.web.squarecdn.com",
            "https://www.paypal.com",
            "https://www.paypalobjects.com",
        ],
        "style-src": [
            "'self'",
            "https://web.squarecdn.com",
            "https://sandbox.web.squarecdn.com",
            "https://www.paypalobjects.com",
        ],
        "img-src": ["'self'", "data:", "https://www.paypalobjects.com"],
        "font-src": ["'self'", "data:"],
        "connect-src": [
            "'self'",
            "wss:",
            "https://connect.squareup.com",
            "https://connect.squareupsandbox.com",
            "https://api-m.paypal.com",
            "https://api-m.sandbox.paypal.com",
        ],
        "frame-src": [
            "'self'",
            "https://web.squarecdn.com",
            "https://sandbox.web.squarecdn.com",
            "https://www.paypal.com",
            "https://www.sandbox.paypal.com",
        ],
        "frame-ancestors": ["'none'"],
        "form-action": ["'self'"],
        "base-uri": ["'self'"],
        "object-src": ["'none'"],
        **({"report-uri": [_CSP_REPORT_URI]} if _CSP_REPORT_URI else {}),
    },
}

# Session Management
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 24  # 24hr
# Write-through cache session (redis cache, persisted to db).
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# Default email to display as part of error messages
APIS_DEFAULT_EMAIL = os.getenv("APIS_DEFAULT_EMAIL", "registration@example.com")

# Sandbox values - DEPRECATED
AUTHNET_NAME = ""
AUTHNET_TRANSACTIONKEY = ""

# Sandbox values = DO NOT check in production ids
SQUARE_APPLICATION_ID = os.environ.get("SQUARE_APPLICATION_ID")
SQUARE_APPLICATION_SECRET = os.environ.get("SQUARE_APPLICATION_SECRET")
SQUARE_ACCESS_TOKEN = os.environ.get("SQUARE_ACCESS_TOKEN")
SQUARE_LOCATION_ID = os.environ.get("SQUARE_LOCATION_ID")
SQUARE_CURRENCY = os.getenv("SQUARE_CURRENCY", "USD")
SQUARE_ENVIRONMENT = os.getenv("SQUARE_ENVIRONMENT", "sandbox")  # Or "production"
SQUARE_WEBHOOK_SIGNATURE_KEY = os.getenv("SQUARE_WEBHOOK_SIGNATURE_KEY", "unset")
PAYPAL_CLIENT_ID = os.environ["PAYPAL_CLIENT_ID"]
PAYPAL_CLIENT_SECRET = os.environ["PAYPAL_CLIENT_SECRET"]
PAYPAL_CURRENCY = os.getenv("PAYPAL_CURRENCY", "USD")
PAYPAL_ENVIRONMENT = os.getenv("PAYPAL_ENVIRONMENT", "sandbox")  # Or "production"
PAYPAL_WEBHOOK_ID = os.getenv("PAYPAL_WEBHOOK_ID", "")
E2E_MODE = eval_bool(os.getenv("E2E_MODE", "False"))

# Sandbox values - DO NOT check in production credentials
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = eval_bool(os.getenv("EMAIL_USE_TLS", "True"))

# Print handler for cash drawer and receipts
REGISTER_SQUARE_LOCATION = os.getenv("REGISTER_SQUARE_LOCATION", SQUARE_LOCATION_ID)
REGISTER_DEFAULT_WEBVIEW = os.getenv(
    "REGISTER_DEFAULT_WEBVIEW", "https://www.example.com/code-of-conduct-embed/"
)

# Cron metrics recording provider and settings
APIS_METRICS_BACKEND = os.getenv("APIS_METRICS_BACKEND", "InfluxDBReporter")
APIS_METRICS_SETTINGS = {
    "database": os.getenv("INFLUXDB_DATABASE", "apis"),
    "host": os.getenv("INFLUXDB_HOST", "localhost"),
}

# MQTT for cash-drawer worker
MQTT_BROKER = {
    "host": os.getenv("MQTT_BROKER_HOST", "localhost"),
    "port": int(os.getenv("MQTT_BROKER_PORT", 1883)),
    "keepalive": int(os.getenv("MQTT_BROKER_KEEPALIVE", 60)),
}

if eval_bool(os.getenv("MQTT_BROKER_TLS", "False")):
    MQTT_BROKER["tls"] = {"ca_certs": "/etc/ssl/certs/ca-certificates.crt"}

# This URL is passed to browsers to connect to MQTT over websockets for push messages
MQTT_EXTERNAL_BROKER = os.getenv("MQTT_EXTERNAL_BROKER", "/mqtt")

MQTT_JWT_SECRET = os.getenv("MQTT_JWT_SECRET")
MQTT_JWT_ALGORITHM = os.getenv("MQTT_JWT_ALGORITHM", "HS256")

ENVIRONMENT_NAME = os.getenv("ENVIRONMENT_NAME", "Production Server")
ENVIRONMENT_COLOR = os.getenv("ENVIRONMENT_COLOR", "#FF0000")
ENVIRONMENT_TEXT_COLOR = os.getenv("ENVIRONMENT_TEXT_COLOR", "#00FF00")
ENVIRONMENT_FLOAT = os.getenv("ENVIRONMENT_FLOAT", False)

GOTENBERG_HOST = os.getenv("GOTENBERG_HOST", None)

DJANGO_VITE_STATIC_URL_PREFIX = "bundler"

VALIDATE_TEMPLATES_IGNORE_APPS = ["allauth"]
