"""
Django settings for fm_eventmanager project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from idempotency_key import status

eval_bool = lambda x: x.lower() in ("true", "1", "t", "y", "yes")

SENTRY_ENABLED = eval_bool(os.environ.get("SENTRY_ENABLED", ""))
if SENTRY_ENABLED:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    # Drop attacker- or user-supplied data from events before they leave the
    # process. CLAUDE.md forbids PII / payment / webhook bodies in logs.
    # Sentry's default scrubber redacts known-secret keys but does not drop
    # raw POST bodies or cookies; do both here.
    def _sentry_before_send(event, hint):
        request = (event or {}).get("request") or {}
        # Webhook handlers (Square, PayPal) re-read request.body; Sentry's
        # capture would otherwise serialize it. Drop the body and any cookies
        # entirely.
        request.pop("data", None)
        request.pop("cookies", None)
        # Strip any inbound trust headers that might carry session-bound
        # values (Authorization, Cookie). Headers we keep are useful for
        # debugging without being identity-bearing.
        headers = request.get("headers") or {}
        for hkey in list(headers):
            if hkey.lower() in {
                "authorization",
                "cookie",
                "x-csrftoken",
                "idempotency-key",
                "x-firebase-token",
            }:
                headers[hkey] = "[scrubbed]"
        return event

    sentry_sdk.init(
        dsn=os.environ["SENTRY_DSN"],
        integrations=[DjangoIntegration()],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production,
        traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", 0.01)),
        # NEVER attach request.user, IP, headers, or cookies to events by
        # default. Operators can opt back in by setting
        # SENTRY_SEND_DEFAULT_PII=true, but the OWASP / ASVS V7 / CLAUDE.md
        # baseline is OFF.
        send_default_pii=eval_bool(os.environ.get("SENTRY_SEND_DEFAULT_PII", "False")),
        before_send=_sentry_before_send,
        # By default the SDK will try to use the SENTRY_RELEASE
        # environment variable, or infer a git commit
        # SHA as release, however you may want to set
        # something more human-readable.
        # release="myapp@1.0.0",
        auto_session_tracking=False,
    )

    SENTRY_RELEASE = os.environ.get("SENTRY_RELEASE", "local")
    SENTRY_ENVIRONMENT = os.environ.get("SENTRY_ENVIRONMENT")
    SENTRY_FRONTEND_DSN = os.environ.get("SENTRY_FRONTEND_DSN")
    SENTRY_USER_REPORTS = True

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = eval_bool(os.getenv("DJANGO_DEBUG", "False"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            #'filters': ['require_debug_true'],
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "django": {
            "handlers": ["console"],
            "propagate": True,
        },
    },
}

# Get loglevel from env
LOGLEVEL = os.getenv("DJANGO_LOGLEVEL", "info").upper()

if eval_bool(os.getenv("APIS_ADMIN_EMAIL_HANDLER", "False")):
    ADMINS = [
        (
            os.getenv("APIS_ADMIN_NAME", os.getenv("APIS_ADMIN_EMAIL")),
            os.getenv("APIS_ADMIN_EMAIL"),
        ),
    ]
SERVER_EMAIL = os.getenv("DJANGO_SERVER_EMAIL", "no-reply@example.com")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", SERVER_EMAIL)


# ALLOWED_HOSTS / CSRF_TRUSTED_ORIGINS — explicit allowlists, no wildcards in
# production. ASVS V14.1.1 / OWASP A05.
#
#   - DEBUG=True (local dev / test):
#       fall back to {localhost, 127.0.0.1, [::1], testserver} so runserver
#       and the Django test client work without per-developer setup.
#   - DEBUG=False (any deployment):
#       the deployer MUST provide ALLOWED_HOSTS (comma-separated FQDNs) and
#       CSRF_TRUSTED_ORIGINS (comma-separated https:// origins). A missing
#       value is a deploy-blocking error.
def _split_env(name):
    raw = os.environ.get(name, "")
    return [item.strip() for item in raw.split(",") if item.strip()]


ALLOWED_HOSTS = _split_env("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _split_env("CSRF_TRUSTED_ORIGINS")

if DEBUG:
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "testserver"]
    if not CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = ["http://localhost", "http://127.0.0.1"]
else:
    if not ALLOWED_HOSTS:
        raise RuntimeError(
            "ALLOWED_HOSTS must be set (comma-separated FQDNs) when DEBUG=False. "
            "Refusing to start with a wildcard or empty allowlist."
        )
    if not CSRF_TRUSTED_ORIGINS:
        raise RuntimeError(
            "CSRF_TRUSTED_ORIGINS must be set (comma-separated https:// origins) "
            "when DEBUG=False."
        )
    # Reject wildcard literals in production.
    if any(h == "*" or h.startswith("*.") and h == "*" for h in ALLOWED_HOSTS):
        raise RuntimeError("ALLOWED_HOSTS must not contain '*' in production.")
    if any(o in ("http://*", "https://*", "*") for o in CSRF_TRUSTED_ORIGINS):
        raise RuntimeError(
            "CSRF_TRUSTED_ORIGINS must not contain wildcards in production."
        )

# --- Trusted-proxy / client-IP plumbing ---------------------------------
# nginx (the in-container reverse proxy) is the trust boundary. It always
# overwrites X-Real-IP and X-Forwarded-For with the real client IP after
# the realip module has rewritten $remote_addr from a trusted upstream
# (Application Gateway / Front Door / nginx-ingress). Django and allauth
# read X-Real-IP via ALLAUTH_TRUSTED_CLIENT_IP_HEADER below.
#
# To override (e.g. when Front Door is the only edge and X-Azure-ClientIP
# is the canonical header), set TRUSTED_CLIENT_IP_HEADER in env. Setting
# it to the empty string disables the header read and falls back to
# REMOTE_ADDR (used by the test suite — see Makefile TEST_ENV).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    "django_admin_env_notice",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.postgres",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "widget_tweaks",
    "mathfilters",
    "import_export",
    "django_extensions",
    "maintenance_mode",
    "allauth",
    "allauth.account",
    "allauth.mfa",
    "registration",
    "nested_inline",
    "django_prometheus",
    "django_vite",
    "csp",
    "axes",  # P1.10: brute-force protection on auth endpoints
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Fail closed if the trusted edge didn't supply a real client IP.
    # See fm_eventmanager.middleware.RequireClientIPMiddleware. Position is
    # after Common (so APPEND_SLASH redirects still work for unauth paths)
    # and before CSRF / Auth (so we don't burn session/CSRF state on
    # requests we are about to reject).
    "fm_eventmanager.middleware.RequireClientIPMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "csp.middleware.CSPMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "idempotency_key.middleware.ExemptIdempotencyKeyMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
    # axes.middleware.AxesMiddleware MUST be the last middleware in the
    # list per https://django-axes.readthedocs.io/ — it depends on the
    # AuthenticationMiddleware-set request.user and on having seen the
    # full response chain to record outcomes. Placed even after the
    # Prometheus After middleware so axes can also see metric label
    # state if it ever needs to.
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    "axes.middleware.AxesMiddleware",
]

# django-debug-toolbar is dev-only. Adding the app/middleware unconditionally
# (a) leaks SQL / settings / stacks to anyone who can reach the listener if
# DEBUG flips to True for any reason, and (b) crashes import in any prod
# image that doesn't have django-debug-toolbar installed (it's in the dev
# group of pyproject.toml). Gate both entries here.
if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]
    # debug_toolbar wants to sit just after CommonMiddleware. Insert at a
    # known position rather than appending so it works correctly.
    _DT_MW = "debug_toolbar.middleware.DebugToolbarMiddleware"
    if _DT_MW not in MIDDLEWARE:
        MIDDLEWARE.insert(
            MIDDLEWARE.index("django.middleware.clickjacking.XFrameOptionsMiddleware")
            + 1,
            _DT_MW,
        )

ROOT_URLCONF = "fm_eventmanager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "maintenance_mode.context_processors.maintenance_mode",
                "registration.context_processors.square_environment",
                "django_admin_env_notice.context_processors.from_settings",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": os.getenv("DATABASE_NAME", "apis"),
        "USER": os.getenv("DATABASE_USER", "apis"),
        "PASSWORD": os.getenv("DATABASE_PASS", "secret"),
        "HOST": os.getenv("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT", "5432"),
        "OPTIONS": {
            "pool": eval_bool(os.getenv("DJANGO_DATABASE_POOL", "True")),
            # ASVS V9.1.1 / OWASP "Transport Layer Protection": enforce TLS
            # to the database in transit. Driven by env so the local
            # docker-compose Postgres (which doesn't terminate TLS) can use
            # 'prefer'. Production targets (Azure Database for PostgreSQL
            # Flexible Server, AWS RDS, etc.) MUST set DATABASE_SSLMODE=require
            # — or stronger ('verify-ca' / 'verify-full' once the CA bundle
            # is mounted). See psycopg docs for libpq sslmode semantics.
            "sslmode": os.getenv("DATABASE_SSLMODE", "prefer"),
        },
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("DJANGO_REDIS_URL", "redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": os.getenv("DJANGO_REDIS_KEY_PREFIX", "apis"),
    }
}


# Celery
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/2")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/2")
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_WORKER_SEND_TASK_EVENTS = eval_bool(
    os.getenv("CELERY_WORKER_SEND_TASK_EVENTS", "True")
)
CELERY_TASK_SEND_SENT_EVENT = eval_bool(
    os.getenv("CELERY_TASK_SEND_SENT_EVENT", "True")
)


# Prometheus metrics
PROMETHEUS_METRICS_EXPORT_PORT_RANGE = range(81, 90)
# Bind the django-prometheus exporter to loopback only. The metrics
# endpoint exposes per-route latency, query counts, and (depending on
# configuration) request labels — all internal-only data. Per CLAUDE.md
# operational rule, port 81 must NEVER be reachable from the public
# internet. In Azure deployments scrape via:
#   - sidecar in the same pod (AKS), or
#   - metrics-server / Container Insights, or
#   - VNET-private Prometheus targeting only the management subnet.
# Override with PROMETHEUS_METRICS_EXPORT_ADDRESS=0.0.0.0 only if a
# scraper is reachable inside the container's network namespace.
PROMETHEUS_METRICS_EXPORT_ADDRESS = os.getenv(
    "PROMETHEUS_METRICS_EXPORT_ADDRESS", "127.0.0.1"
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
#
# Required by ASVS V2.1.1 / OWASP A07. Django runs these validators in
# admin user-create / user-change forms, in `manage.py createsuperuser`
# (interactive mode), and in any code that calls
# `django.contrib.auth.password_validation.validate_password`. Programmatic
# `User.objects.create_*` / `User.set_password()` do NOT run validators
# (Django's design), so existing tests that build fixture users with short
# passwords continue to work.
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TZ", "UTC")

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # django-axes wraps every authenticate() call to record failures and
    # block lockouts. Per axes docs it MUST be first so it can short-
    # circuit an authentication attempt during a lockout window.
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_ADAPTER = "fm_eventmanager.adapters.account.RegistrationAccountAdapter"

# --- django-axes: brute-force protection ---------------------------------
# OWASP A07 (Identification and Authentication Failures) / ASVS V2.2.1.
#
# AXES_FAILURE_LIMIT       : after N consecutive failed logins, lock out.
# AXES_COOLOFF_TIME        : lockout duration (hours when set as int).
# AXES_LOCKOUT_PARAMETERS  : key the lockout off (username, ip_address) so
#                            a single attacker IP cannot trigger lockout
#                            for unrelated users sharing that IP, and a
#                            user is only locked from the IP they keep
#                            failing from.
# AXES_RESET_ON_SUCCESS    : clear failure count after a successful login,
#                            so legitimate users don't accumulate state.
# AXES_CLIENT_IP_CALLABLE  : delegate IP resolution to our central helper
#                            (registration.views.common.get_client_ip),
#                            which reads ALLAUTH_TRUSTED_CLIENT_IP_HEADER
#                            (X-Real-IP) — the same trust contract every
#                            other IP-derived control uses. Otherwise axes
#                            would re-implement IP detection against the
#                            wrong header.
AXES_FAILURE_LIMIT = int(os.getenv("AXES_FAILURE_LIMIT", "5"))
AXES_COOLOFF_TIME = int(os.getenv("AXES_COOLOFF_TIME_HOURS", "1"))
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_CALLABLE = None
AXES_CLIENT_IP_CALLABLE = "fm_eventmanager.middleware.axes_client_ip"
# Don't fail open if the DB is unreachable when checking lockout state.
AXES_HANDLER = "axes.handlers.database.AxesDatabaseHandler"

# allauth has its own login_failed rate limit (default 10/m/ip,5/300s/key)
# that conflicts with django-axes. Defer to axes for failed-login lockout
# (per-(username,ip) with configurable cooldown) and keep allauth's
# OTHER rate limits (signup, password reset, MFA, etc.) intact.
ACCOUNT_RATE_LIMITS = {
    # Inherit allauth's defaults except for the conflicting login_failed.
    # Setting it to an empty string disables it (allauth contract).
    "login_failed": "",
    "signup": "20/m/ip",
    "reset_password": "20/m/ip,5/m/key",
    "reset_password_from_key": "20/m/ip",
    "manage_email": "10/m/user",
    "change_password": "5/m/user",
    "change_phone": "1/m/user",
    "request_login_code": "20/m/ip,3/m/key",
    "login": "30/m/ip",
    "reauthenticate": "10/m/user",
    "confirm_email": "1/180s/key",
    "verify_phone": "1/30s/key,3/m/ip",
}

MFA_SUPPORTED_TYPES = ["totp", "webauthn", "recovery_codes"]
MFA_PASSKEY_LOGIN_ENABLED = True
MFA_ADAPTER = "allauth.mfa.adapter.DefaultMFAAdapter"

ALLAUTH_TRUSTED_CLIENT_IP_HEADER = os.getenv("TRUSTED_CLIENT_IP_HEADER", "X-Real-IP")

LOGIN_REDIRECT_URL = "admin:index"

IDEMPOTENCY_KEY = {
    # Specify the key encoder class to be used for idempotency keys.
    # If not specified then defaults to 'idempotency_key.encoders.BasicKeyEncoder'
    "ENCODER_CLASS": "idempotency_key.encoders.BasicKeyEncoder",
    # Set the response code on a conflict.
    # If not specified this defaults to HTTP_409_CONFLICT
    # If set to None then the original request's status code is used.
    "CONFLICT_STATUS_CODE": status.HTTP_409_CONFLICT,
    # Allows the idempotency key header sent from the client to be changed
    "HEADER": "HTTP_IDEMPOTENCY_KEY",
    "STORAGE": {
        # Specify the storage class to be used for idempotency keys
        # If not specified then defaults to 'idempotency_key.storage.MemoryKeyStorage'
        "CLASS": "idempotency_key.storage.CacheKeyStorage",
        # Name of the django cache configuration to use for the CacheStorageKey storage
        # class.
        # This can be overriden using the @idempotency_key(cache_name='MyCacheName')
        # view/viewset function decorator.
        "CACHE_NAME": "default",
        # When the response is to be stored you have the option of deciding when this
        # happens based on the responses status code. If the response status code
        # matches one of the statuses below then it will be stored.
        # The statuses below are the defaults used if this setting is not specified.
        "STORE_ON_STATUSES": [
            status.HTTP_200_OK,
            status.HTTP_201_CREATED,
            status.HTTP_202_ACCEPTED,
            status.HTTP_203_NON_AUTHORITATIVE_INFORMATION,
            status.HTTP_204_NO_CONTENT,
            status.HTTP_205_RESET_CONTENT,
            status.HTTP_206_PARTIAL_CONTENT,
            status.HTTP_207_MULTI_STATUS,
        ],
    },
    # The following settings deal with the process/thread lock that can be placed around the cache storage object
    # to ensure that multiple threads do not try to call the same view/viewset method at the same time.
    "LOCK": {
        # Specify the key object locking class to be used for locking access to the cache storage object.
        # If not specified then defaults to 'idempotency_key.locks.basic.ThreadLock'
        "CLASS": "idempotency_key.locks.redis.MultiProcessRedisLock",
        # Location of the Redis server if MultiProcessRedisLock is used otherwise this is ignored.
        # The host name can be specified or both the host name and the port separated by a colon ':'
        "LOCATION": os.getenv("IDEMPOTENCY_KEY_LOCK_LOCATION", "redis://redis:6379"),
        # The unique name to be used across processes for the lock. Only used by the MultiProcessRedisLock class
        "NAME": os.getenv("IDEMPOTENCY_KEY_LOCK_NAME", "APISLock"),
        # The maximum time to live for the lock. If a lock is given and is never released this timeout forces the release
        # The lock time is in seconds and the default is None which means lock until it is manually released
        "TTL": None,
        # The use of a lock around the storage object so that only one thread at a time can access it.
        # By default this is set to true. WARNING: setting this to false may allow duplicate calls to occur if the timing
        # is right.
        "ENABLE": True,
        # If the ENABLE_LOCK setting is True above then this represents the timeout (in seconds as a floating point number)
        # to occur before the thread gives up waiting. If a timeout occurs the middleware will return a HTTP_423_LOCKED
        # response.
        "TIMEOUT": 0.1,
    },
}

# django-maintenance-mode state.
#
# Default backend persists state to a file under /app/, which fails when
# the container runs with `read_only: true` (CIS Docker 5.12). Switch to
# the Redis cache backend so state survives container restarts AND is
# safe under a read-only root filesystem. The CacheBackend uses the
# `default` cache (django_redis → Redis), keyed by `"maintenance_mode"`.
MAINTENANCE_MODE_STATE_BACKEND = os.getenv(
    "MAINTENANCE_MODE_STATE_BACKEND",
    "maintenance_mode.backends.CacheBackend",
)
# Fallback file path — only consulted when MAINTENANCE_MODE_STATE_BACKEND
# is explicitly set to a file-based backend (LocalFileBackend / similar).
# Default goes to /tmp (the tmpfs allowlisted under read-only fs).
MAINTENANCE_MODE_STATE_FILE_PATH = os.getenv(
    "MAINTENANCE_MODE_STATE_FILE_PATH",
    "/tmp/maintenance_mode_state.txt",
)
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True
MAINTENANCE_MODE_IGNORE_URLS = ("^/accounts/",)

if DEBUG:
    # Adds docker NAT routers and any internal upstream proxies as internal IPs to enable the debug toolbar
    import socket  # only if you haven't already imported this

    INTERNAL_IPS = ["127.0.0.1"]
    for proxy_host in (socket.gethostname(), os.getenv("INTERNAL_PROXY_HOST")):
        if proxy_host:
            hostname, _, ips = socket.gethostbyname_ex(proxy_host)
            INTERNAL_IPS += [ip[: ip.rfind(".")] + ".1" for ip in ips] + ips

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/app/apis/static/"
# NOTE: do NOT add a ("bundler", ...) STATICFILES_DIRS entry here. The Vite
# build in Dockerfile's ``assets`` stage outputs to
# ``registration/static/bundler/`` — Django's AppDirectoriesFinder picks that
# up automatically because ``registration`` is an INSTALLED_APP. Pointing
# STATICFILES_DIRS at ``/app/apis/static/bundler`` is circular (that path is
# ``collectstatic``'s destination, not its source) and triggers W004.

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "fm_eventmanager.file_storage.SelectiveManifestStaticFilesStorage",
    },
}

# --- Cookie / transport hardening ---------------------------------------
# OWASP A02 / A05, ASVS V3.4 / V9.1, OWASP "Secure Cookie Attribute" and
# "Transport Layer Protection" cheat sheets.
#
# The Secure-flagged settings below DEPEND on Fix 1 (the proxy / header
# pipeline) being live so Django can see X-Forwarded-Proto and decide that
# the request is HTTPS. They are gated on `not DEBUG` so local runserver
# (plain HTTP) does not redirect-loop or refuse to send cookies.

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = (
    "Lax"  # Strict would break PayPal/Square post-payment redirects.
)
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    # HSTS — 1 year by default, includeSubDomains on. Preload OFF until the
    # operator explicitly opts in; submitting to hstspreload.org is a
    # one-way commitment so we don't enable it implicitly.
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", str(60 * 60 * 24 * 365)))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = eval_bool(
        os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True")
    )
    SECURE_HSTS_PRELOAD = eval_bool(os.getenv("SECURE_HSTS_PRELOAD", "False"))

# --- Content Security Policy (report-only) ------------------------------
# OWASP A03 (XSS) / OWASP CSP cheat sheet / ASVS V14.4.
#
# We ship in *report-only* mode for the first phase: the policy below is
# strict (no unsafe-inline, no unsafe-eval), but violations only generate
# reports — they don't block resources. Once the templates are clean
# (or nonced), flip CONTENT_SECURITY_POLICY_REPORT_ONLY to
# CONTENT_SECURITY_POLICY to enforce.
#
# Set CSP_REPORT_URI to the URL of your report collector (Sentry's CSP
# endpoint, an internal endpoint, etc.) to receive violation reports. When
# unset, no `report-uri` is emitted (browsers will still apply the policy
# but reports are silent).
_CSP_REPORT_URI = os.getenv("CSP_REPORT_URI", "")

CONTENT_SECURITY_POLICY_REPORT_ONLY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        # Vite produces hashed external scripts under /static/; they match
        # 'self'. Square and PayPal SDKs load from their own CDNs — add them
        # explicitly. No 'unsafe-inline' / 'unsafe-eval'.
        "script-src": [
            "'self'",
            "https://web.squarecdn.com",
            "https://sandbox.web.squarecdn.com",
            "https://www.paypal.com",
            "https://www.paypalobjects.com",
        ],
        # style-src will likely report violations from inline `style=""` in
        # admin templates — that's expected and is what tells us what to
        # clean up. Keep strict.
        "style-src": [
            "'self'",
            "https://web.squarecdn.com",
            "https://sandbox.web.squarecdn.com",
            "https://www.paypalobjects.com",
        ],
        "img-src": ["'self'", "data:", "https://www.paypalobjects.com"],
        "font-src": ["'self'", "data:"],
        # XHR / fetch destinations: app origin, MQTT broker over WSS, payment
        # SDK API endpoints, gotenberg if exposed.
        "connect-src": [
            "'self'",
            "wss:",
            "https://connect.squareup.com",
            "https://connect.squareupsandbox.com",
            "https://api-m.paypal.com",
            "https://api-m.sandbox.paypal.com",
        ],
        # Embedded payment iframes from Square / PayPal.
        "frame-src": [
            "'self'",
            "https://web.squarecdn.com",
            "https://sandbox.web.squarecdn.com",
            "https://www.paypal.com",
            "https://www.sandbox.paypal.com",
        ],
        "frame-ancestors": ["'none'"],
        "form-action": ["'self'"],
        "base-uri": ["'self'"],
        "object-src": ["'none'"],
        # report-uri is only set when CSP_REPORT_URI is configured.
        **({"report-uri": [_CSP_REPORT_URI]} if _CSP_REPORT_URI else {}),
    },
}

# Session Management
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 24  # 24hr
# Write-through cache session (redis cache, persisted to db).
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# Default email to display as part of error messages
APIS_DEFAULT_EMAIL = os.getenv("APIS_DEFAULT_EMAIL", "registration@example.com")

# Sandbox values - DEPRECATED
AUTHNET_NAME = ""
AUTHNET_TRANSACTIONKEY = ""

# Sandbox values = DO NOT check in production ids
SQUARE_APPLICATION_ID = os.environ.get("SQUARE_APPLICATION_ID")
SQUARE_APPLICATION_SECRET = os.environ.get("SQUARE_APPLICATION_SECRET")
SQUARE_ACCESS_TOKEN = os.environ.get("SQUARE_ACCESS_TOKEN")
SQUARE_LOCATION_ID = os.environ.get("SQUARE_LOCATION_ID")
SQUARE_CURRENCY = os.getenv("SQUARE_CURRENCY", "USD")
SQUARE_ENVIRONMENT = os.getenv("SQUARE_ENVIRONMENT", "production")  # Or "sandbox"
SQUARE_WEBHOOK_SIGNATURE_KEY = os.getenv("SQUARE_WEBHOOK_SIGNATURE_KEY", "unset")
PAYPAL_CLIENT_ID = os.environ.get("PAYPAL_CLIENT_ID", "")
PAYPAL_CLIENT_SECRET = os.environ.get("PAYPAL_CLIENT_SECRET", "")
PAYPAL_CURRENCY = os.getenv("PAYPAL_CURRENCY", "USD")
PAYPAL_ENVIRONMENT = os.getenv("PAYPAL_ENVIRONMENT", "production")  # Or "sandbox"

# Sandbox values - DO NOT check in production credentials
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = eval_bool(os.getenv("EMAIL_USE_TLS", "True"))

# Print handler for cash drawer and receipts
REGISTER_SQUARE_LOCATION = os.getenv("REGISTER_SQUARE_LOCATION", SQUARE_LOCATION_ID)
REGISTER_DEFAULT_WEBVIEW = os.getenv(
    "REGISTER_DEFAULT_WEBVIEW", "https://www.example.com/code-of-conduct-embed/"
)

# Cron metrics recording provider and settings
APIS_METRICS_BACKEND = os.getenv("APIS_METRICS_BACKEND", "InfluxDBReporter")
APIS_METRICS_SETTINGS = {
    "database": os.getenv("INFLUXDB_DATABASE", "apis"),
    "host": os.getenv("INFLUXDB_HOST", "localhost"),
}

# MQTT for cash-drawer worker
MQTT_BROKER = {
    "host": os.getenv("MQTT_BROKER_HOST", "localhost"),
    "port": int(os.getenv("MQTT_BROKER_PORT", 1883)),
    "keepalive": int(os.getenv("MQTT_BROKER_KEEPALIVE", 60)),
}

if eval_bool(os.getenv("MQTT_BROKER_TLS", "False")):
    MQTT_BROKER["tls"] = {"ca_certs": "/etc/ssl/certs/ca-certificates.crt"}

# This URL is passed to browsers to connect to MQTT over websockets for push messages
MQTT_EXTERNAL_BROKER = os.getenv("MQTT_EXTERNAL_BROKER", "/mqtt")

MQTT_JWT_SECRET = os.getenv("MQTT_JWT_SECRET")
MQTT_JWT_ALGORITHM = os.getenv("MQTT_JWT_ALGORITHM", "HS256")

ENVIRONMENT_NAME = os.getenv("ENVIRONMENT_NAME", "Production Server")
ENVIRONMENT_COLOR = os.getenv("ENVIRONMENT_COLOR", "#FF0000")
ENVIRONMENT_TEXT_COLOR = os.getenv("ENVIRONMENT_TEXT_COLOR", "#00FF00")
ENVIRONMENT_FLOAT = os.getenv("ENVIRONMENT_FLOAT", False)

GOTENBERG_HOST = os.getenv("GOTENBERG_HOST", None)

DJANGO_VITE_STATIC_URL_PREFIX = "bundler"

VALIDATE_TEMPLATES_IGNORE_APPS = ["allauth"]
